// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Extracts key discussion points and takeaways from a given conversation, including relevant quotes.
 *
 * - extractKeyPoints - A function that extracts key points from the conversation.
 * - ExtractKeyPointsInput - The input type for the extractKeyPoints function.
 * - ExtractKeyPointsOutput - The return type for the extractKeyPoints function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExtractKeyPointsInputSchema = z.object({
  conversation: z
    .string()
    .describe('The entire conversation text from which key points need to be extracted.'),
});
export type ExtractKeyPointsInput = z.infer<typeof ExtractKeyPointsInputSchema>;

const ExtractKeyPointsOutputSchema = z.object({
  keyPoints: z
    .array(z.string())
    .describe('A list of key discussion points and takeaways from the conversation.'),
  quotes: z
    .array(z.string())
    .describe('A list of relevant quotes that highlight the key discussion points.'),
});
export type ExtractKeyPointsOutput = z.infer<typeof ExtractKeyPointsOutputSchema>;

export async function extractKeyPoints(input: ExtractKeyPointsInput): Promise<ExtractKeyPointsOutput> {
  return extractKeyPointsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'extractKeyPointsPrompt',
  input: {schema: ExtractKeyPointsInputSchema},
  output: {schema: ExtractKeyPointsOutputSchema},
  prompt: `You are an expert in conversation analysis. Your task is to extract the key discussion points and takeaways from the following conversation. Also, provide relevant quotes that highlight these points.

Conversation:
{{conversation}}

Key Discussion Points and Takeaways:
- Key Points:
{{{keyPoints}}}
- Quotes:
{{{quotes}}}`, 
});

const extractKeyPointsFlow = ai.defineFlow(
  {
    name: 'extractKeyPointsFlow',
    inputSchema: ExtractKeyPointsInputSchema,
    outputSchema: ExtractKeyPointsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
